version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(frontend)"

  - package-ecosystem: "pip"
    directory: "/services/converter"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(python)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(ci)"
