// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: paper.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PdfConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfContent    []byte                 `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfConvertRequest) Reset() {
	*x = PdfConvertRequest{}
	mi := &file_paper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfConvertRequest) ProtoMessage() {}

func (x *PdfConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfConvertRequest.ProtoReflect.Descriptor instead.
func (*PdfConvertRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{0}
}

func (x *PdfConvertRequest) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

func (x *PdfConvertRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ConvertProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Markdown      string                 `protobuf:"bytes,3,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertProgress) Reset() {
	*x = ConvertProgress{}
	mi := &file_paper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertProgress) ProtoMessage() {}

func (x *ConvertProgress) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertProgress.ProtoReflect.Descriptor instead.
func (*ConvertProgress) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConvertProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ConvertProgress) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *ConvertProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_paper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type PaperMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Authors       []string               `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
	Abstract      string                 `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Keywords      []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	PublishedYear string                 `protobuf:"bytes,5,opt,name=published_year,json=publishedYear,proto3" json:"published_year,omitempty"`
	Doi           string                 `protobuf:"bytes,6,opt,name=doi,proto3" json:"doi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperMetadata) Reset() {
	*x = PaperMetadata{}
	mi := &file_paper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperMetadata) ProtoMessage() {}

func (x *PaperMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperMetadata.ProtoReflect.Descriptor instead.
func (*PaperMetadata) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{3}
}

func (x *PaperMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PaperMetadata) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *PaperMetadata) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *PaperMetadata) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *PaperMetadata) GetPublishedYear() string {
	if x != nil {
		return x.PublishedYear
	}
	return ""
}

func (x *PaperMetadata) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

var File_paper_proto protoreflect.FileDescriptor

const file_paper_proto_rawDesc = "" +
	"\n" +
	"\vpaper.proto\x12\x05paper\"P\n" +
	"\x11PdfConvertRequest\x12\x1f\n" +
	"\vpdf_content\x18\x01 \x01(\fR\n" +
	"pdfContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"w\n" +
	"\x0fConvertProgress\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x1a\n" +
	"\bmarkdown\x18\x03 \x01(\tR\bmarkdown\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"-\n" +
	"\x0fMetadataRequest\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\"\xb0\x01\n" +
	"\rPaperMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\aauthors\x18\x02 \x03(\tR\aauthors\x12\x1a\n" +
	"\babstract\x18\x03 \x01(\tR\babstract\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x12%\n" +
	"\x0epublished_year\x18\x05 \x01(\tR\rpublishedYear\x12\x10\n" +
	"\x03doi\x18\x06 \x01(\tR\x03doi2\x90\x01\n" +
	"\x0ePaperConverter\x12=\n" +
	"\aConvert\x12\x18.paper.PdfConvertRequest\x1a\x16.paper.ConvertProgress0\x01\x12?\n" +
	"\x0fExtractMetadata\x12\x16.paper.MetadataRequest\x1a\x14.paper.PaperMetadataB%Z#github.com/khalily/oreader/proto/gob\x06proto3"

var (
	file_paper_proto_rawDescOnce sync.Once
	file_paper_proto_rawDescData []byte
)

func file_paper_proto_rawDescGZIP() []byte {
	file_paper_proto_rawDescOnce.Do(func() {
		file_paper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paper_proto_rawDesc), len(file_paper_proto_rawDesc)))
	})
	return file_paper_proto_rawDescData
}

var file_paper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paper_proto_goTypes = []any{
	(*PdfConvertRequest)(nil), // 0: paper.PdfConvertRequest
	(*ConvertProgress)(nil),   // 1: paper.ConvertProgress
	(*MetadataRequest)(nil),   // 2: paper.MetadataRequest
	(*PaperMetadata)(nil),     // 3: paper.PaperMetadata
}
var file_paper_proto_depIdxs = []int32{
	0, // 0: paper.PaperConverter.Convert:input_type -> paper.PdfConvertRequest
	2, // 1: paper.PaperConverter.ExtractMetadata:input_type -> paper.MetadataRequest
	1, // 2: paper.PaperConverter.Convert:output_type -> paper.ConvertProgress
	3, // 3: paper.PaperConverter.ExtractMetadata:output_type -> paper.PaperMetadata
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paper_proto_init() }
func file_paper_proto_init() {
	if File_paper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paper_proto_rawDesc), len(file_paper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paper_proto_goTypes,
		DependencyIndexes: file_paper_proto_depIdxs,
		MessageInfos:      file_paper_proto_msgTypes,
	}.Build()
	File_paper_proto = out.File
	file_paper_proto_goTypes = nil
	file_paper_proto_depIdxs = nil
}
