// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.11.4
// source: converter/proto/paper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaperConverter_Convert_FullMethodName         = "/paper.PaperConverter/Convert"
	PaperConverter_ExtractMetadata_FullMethodName = "/paper.PaperConverter/ExtractMetadata"
)

// PaperConverterClient is the client API for PaperConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaperConverterClient interface {
	Convert(ctx context.Context, in *PdfConvertRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConvertProgress], error)
	ExtractMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*PaperMetadata, error)
}

type paperConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewPaperConverterClient(cc grpc.ClientConnInterface) PaperConverterClient {
	return &paperConverterClient{cc}
}

func (c *paperConverterClient) Convert(ctx context.Context, in *PdfConvertRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConvertProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaperConverter_ServiceDesc.Streams[0], PaperConverter_Convert_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PdfConvertRequest, ConvertProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaperConverter_ConvertClient = grpc.ServerStreamingClient[ConvertProgress]

func (c *paperConverterClient) ExtractMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*PaperMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperMetadata)
	err := c.cc.Invoke(ctx, PaperConverter_ExtractMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaperConverterServer is the server API for PaperConverter service.
// All implementations must embed UnimplementedPaperConverterServer
// for forward compatibility.
type PaperConverterServer interface {
	Convert(*PdfConvertRequest, grpc.ServerStreamingServer[ConvertProgress]) error
	ExtractMetadata(context.Context, *MetadataRequest) (*PaperMetadata, error)
	mustEmbedUnimplementedPaperConverterServer()
}

// UnimplementedPaperConverterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaperConverterServer struct{}

func (UnimplementedPaperConverterServer) Convert(*PdfConvertRequest, grpc.ServerStreamingServer[ConvertProgress]) error {
	return status.Error(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedPaperConverterServer) ExtractMetadata(context.Context, *MetadataRequest) (*PaperMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractMetadata not implemented")
}
func (UnimplementedPaperConverterServer) mustEmbedUnimplementedPaperConverterServer() {}
func (UnimplementedPaperConverterServer) testEmbeddedByValue()                        {}

// UnsafePaperConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaperConverterServer will
// result in compilation errors.
type UnsafePaperConverterServer interface {
	mustEmbedUnimplementedPaperConverterServer()
}

func RegisterPaperConverterServer(s grpc.ServiceRegistrar, srv PaperConverterServer) {
	// If the following call panics, it indicates UnimplementedPaperConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaperConverter_ServiceDesc, srv)
}

func _PaperConverter_Convert_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PdfConvertRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaperConverterServer).Convert(m, &grpc.GenericServerStream[PdfConvertRequest, ConvertProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaperConverter_ConvertServer = grpc.ServerStreamingServer[ConvertProgress]

func _PaperConverter_ExtractMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperConverterServer).ExtractMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaperConverter_ExtractMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperConverterServer).ExtractMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaperConverter_ServiceDesc is the grpc.ServiceDesc for PaperConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaperConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paper.PaperConverter",
	HandlerType: (*PaperConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractMetadata",
			Handler:    _PaperConverter_ExtractMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Convert",
			Handler:       _PaperConverter_Convert_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "converter/proto/paper.proto",
}
