# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paper.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'paper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpaper.proto\x12\x05paper\":\n\x11PdfConvertRequest\x12\x13\n\x0bpdf_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"T\n\x0f\x43onvertProgress\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x10\n\x08markdown\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"#\n\x0fMetadataRequest\x12\x10\n\x08markdown\x18\x01 \x01(\t\"x\n\rPaperMetadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x02 \x03(\t\x12\x10\n\x08\x61\x62stract\x18\x03 \x01(\t\x12\x10\n\x08keywords\x18\x04 \x03(\t\x12\x16\n\x0epublished_year\x18\x05 \x01(\t\x12\x0b\n\x03\x64oi\x18\x06 \x01(\t2\x90\x01\n\x0ePaperConverter\x12=\n\x07\x43onvert\x12\x18.paper.PdfConvertRequest\x1a\x16.paper.ConvertProgress0\x01\x12?\n\x0f\x45xtractMetadata\x12\x16.paper.MetadataRequest\x1a\x14.paper.PaperMetadataB\x19Z\x17oreader/converter/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027oreader/converter/proto'
  _globals['_PDFCONVERTREQUEST']._serialized_start=22
  _globals['_PDFCONVERTREQUEST']._serialized_end=80
  _globals['_CONVERTPROGRESS']._serialized_start=82
  _globals['_CONVERTPROGRESS']._serialized_end=166
  _globals['_METADATAREQUEST']._serialized_start=168
  _globals['_METADATAREQUEST']._serialized_end=203
  _globals['_PAPERMETADATA']._serialized_start=205
  _globals['_PAPERMETADATA']._serialized_end=325
  _globals['_PAPERCONVERTER']._serialized_start=328
  _globals['_PAPERCONVERTER']._serialized_end=472
# @@protoc_insertion_point(module_scope)
