# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import paper_pb2 as paper__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in paper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaperConverterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_stream(
                '/paper.PaperConverter/Convert',
                request_serializer=paper__pb2.PdfConvertRequest.SerializeToString,
                response_deserializer=paper__pb2.ConvertProgress.FromString,
                _registered_method=True)
        self.ExtractMetadata = channel.unary_unary(
                '/paper.PaperConverter/ExtractMetadata',
                request_serializer=paper__pb2.MetadataRequest.SerializeToString,
                response_deserializer=paper__pb2.PaperMetadata.FromString,
                _registered_method=True)


class PaperConverterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaperConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_stream_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=paper__pb2.PdfConvertRequest.FromString,
                    response_serializer=paper__pb2.ConvertProgress.SerializeToString,
            ),
            'ExtractMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractMetadata,
                    request_deserializer=paper__pb2.MetadataRequest.FromString,
                    response_serializer=paper__pb2.PaperMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paper.PaperConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paper.PaperConverter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaperConverter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/paper.PaperConverter/Convert',
            paper__pb2.PdfConvertRequest.SerializeToString,
            paper__pb2.ConvertProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paper.PaperConverter/ExtractMetadata',
            paper__pb2.MetadataRequest.SerializeToString,
            paper__pb2.PaperMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
